#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N batch_docking
# queue select
#PBS -q workq
#PBS -l nodes=kuhpcgn1
#PBS -l ncpus=32
#PBS -l mpiprocs=1
# Name of stdout output file (default)
#PBS -o batch_docking.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------
PYFILE="batch_docking_mpi.py"
#----------------------------------------------------------
# Get the number of nodes and mpiprocs from PBS environment variables
MPIPROCS=1
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#swap openmpi for mpich since that's what's in the sif
module purge
module load autotools prun/1.3 gnu8/8.3.0 mpich/3.3.1 singularity
export SIFPATH=$HOME/images
export SIFIMG=AMDock_gnina.sif

echo "Starting"
echo '---------------------------------------------' 
#Executing command
LD_LIBRARY_PATH="" mpirun -np $MPIPROCS singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG python $PYFILE --bd_modpath /host_pwd --receptors_dir /host_pwd/downloaded_models --ligands_dir /host_pwd/ligands --protonate_receptors

#End time
end=`date +%s.%N`


RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
