#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=24:host=kuhpcgn1
# Name of stdout output file (default)
#PBS -o md_prod.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=48:00:00 
#----------------------------------------------------------

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

export SIMDIR="zeb_hb_only_sim"
export MD_NAME="zeb_hb"
export TOTAL_TIME_NS=10
export DT=0.004

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
export SIFPATH=$HOME/images
export SIFIMG=gromacs_2024.2-GPU.sif


export GROFILE=$SIMDIR+"/sys_equi/sys_equi/02_equi_CA_LOW/02_equi_CA_LOW_${MD_NAME}.gro"
export TOPFILE=$SIMDIR+"/${MD_NAME}_water_ion.top"

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS
export PROD_DIR = $SIMDIR/${MD_NAME}+"_prod"
mkdir -p $PROD_DIR
# Production run
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	production.py -f $GROFILE -p $TOPFILE -o $PROD_DIR -n $MD_NAME -time $TOTAL_TIME_NS -dt $DT -maxwarn 1 -nt $PBS_NCPUS -gpu_id 0

#End time
end=`date +%s.%N`


echo "NUM_THREADS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
#----------------------------------------------------------
# Communicate job status to a telegram bot
#----------------------------------------------------------
# Create a telegram bot 
# Get TOKEN, CHATID from botfather
# See https://www.cytron.io/tutorial/how-to-create-a-telegram-bot-get-the-api-key-and-chat-id
# Put them into two environment variables TOKEN and CHATID 
# Store them in a config file and source it like below
#----------------------------------------------------------

source ${HOME}/.config/telegram/telegram.conf

LOGIN_NODE=kuhpchn
SSHBIN=/usr/bin/ssh
URL="https://api.telegram.org/bot${TOKEN}/sendMessage"

# Generate the telegram message  text

TEXT="${bell} PBS job exiting now. \
	Job name : ${PBS_JOBNAME}. \
	Job id : ${PBS_JOBID}. \
	Job dir : ${PBS_O_WORKDIR}. \
	Job start-time : ${start}. \
	Job end-time : ${end}. \
	Job runtime : ${RUNTIME} secs."

CMD='curl -s --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10  -d '\
	\""chat_id=${CHATID}&text=${TEXT}&disable_web_page_preview=true&parse_mode=markdown"\""\
	${URL}"

$SSHBIN $LOGIN_NODE $CMD