#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=24:host=kuhpcgn1
# Name of stdout output file (default)
#PBS -o mdrun2.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=48:00:00 
#----------------------------------------------------------

export OMP_NUM_THREADS=24
export MDNAME=md_0_1

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
SIFPATH=$HOME/.config/sifdir
SIFIMG=gromacs_2022.3.sif
GPUID='0'

echo "Starting"
echo '---------------------------------------------'

#Actual MD Dynamics: 
LD_LIBRARY_PATH="" \
	singularity run --nv -B ${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx mdrun -nb gpu -gpu_id $GPUID -pme gpu -pmefft gpu -pin on -v -nt $OMP_NUM_THREADS \
	-deffnm $MDNAME


#End time
end=`date +%s.%N`

echo "OMP_NUM_THREADS=" "$OMP_NUM_THREADS"

RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
#----------------------------------------------------------
# Communicate job status to a telegram bot
#----------------------------------------------------------
# Create a telegram bot 
# Get TOKEN, CHATID from botfather
# See https://www.cytron.io/tutorial/how-to-create-a-telegram-bot-get-the-api-key-and-chat-id
# Put them into two environment variables TOKEN and CHATID 
# Store them in a config file and source it like below
#----------------------------------------------------------

source ${HOME}/.config/telegram/telegram.conf

LOGIN_NODE=kuhpchn
SSHBIN=/usr/bin/ssh
URL="https://api.telegram.org/bot${TOKEN}/sendMessage"

# Generate the telegram message  text

TEXT="${bell} PBS job exiting now. Job name : ${PBS_JOBNAME}. Job id : ${PBS_JOBID}. Job dir : ${PBS_O_WORKDIR}. Job start-time : ${start}. Job end-time : ${end}. Job runtime : ${RUNTIME} secs."

CMD='curl -s --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10  -d '\""chat_id=${CHATID}&text=${TEXT}&disable_web_page_preview=true&parse_mode=markdown"\"" ${URL}"

$SSHBIN $LOGIN_NODE $CMD