#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l nodes=kuhpcgn2
#PBS -l ncpus=32
#PBS -l mpiprocs=1
# Name of stdout output file (default)
#PBS -o mdsim_1.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

# List of simulation directories

CONDA_ENV_NAME="biobb_wf_protein-complex_md_setup"

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda

export PYFILE=$HOME/gitrepos/gromacs_sims/scripts/biobb_protein_ligand_simulation.py

echo "Starting"
echo '---------------------------------------------'

conda run -n $CONDA_ENV_NAME $PYFILE --input_structure $HOME/gitrepos/gromacs_sims/Antimicrobial_Peptides/Pseudomonas_antibiotics/simulation/simulation_complexes/pbppen1999.pdb --ligand_code PEN --outdir pbppen1999 --nprocs $PBS_NCPUS --usegpu --protonated
conda run -n $CONDA_ENV_NAME $PYFILE --input_structure $HOME/gitrepos/gromacs_sims/Antimicrobial_Peptides/Pseudomonas_antibiotics/simulation/simulation_complexes/pbppen2018.pdb --ligand_code PEN --outdir pbppen2018 --nprocs $PBS_NCPUS --usegpu --protonated
conda run -n $CONDA_ENV_NAME $PYFILE --input_structure $HOME/gitrepos/gromacs_sims/Antimicrobial_Peptides/Pseudomonas_antibiotics/simulation/simulation_complexes/pbpmez2018.pdb --ligand_code MEZ --outdir pbpmez2018 --nprocs $PBS_NCPUS --usegpu --protonated

#End time
end=`date +%s.%N`

echo "NUM_CPUS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
