#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=24:mpiprocs=24:host=kuhpcgn1
# Name of stdout output file (default)
#PBS -o mdsim.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

# List of simulation directories
#directories=( "aminostep2012" "dir2" "dir3" )
directories=( "aminostep2012" )

CONDA_ENV_NAME="biobb_wf_protein-complex_md_setup"

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda


echo "Starting"
echo '---------------------------------------------'

#Executing command
for dir in "${directories[@]}"; do
	echo "Processing directory: $dir"
	for notebook in "$dir"/*.ipynb; do
		if [[ -f "$notebook" ]]; then
			echo "Executing notebook: $notebook"
			conda run -n $CONDA_ENV_NAME jupyter nbconvert --to notebook --execute "$notebook"
		else
			echo "No notebooks found in $dir"
		fi
	done
done

#End time
end=`date +%s.%N`

echo "NUM_CPUS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
