#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N batch_mds
# queue select
#PBS -q workq
#PBS -l nodes=kuhpcgn2
#PBS -l ncpus=48
#PBS -l mpiprocs=2
# Name of stdout output file (default)
#PBS -o batch_mdsim.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

# List of simulation directories

CONDA_ENV_NAME="biobb_wf_protein-complex_md_setup"

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

MPIPROCS=2
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
module purge #Get rid of all interfering modules
echo "Purged all modules"
#Load cuda
module load cuda

export PYFILE=$PBS_O_WORKDIR/mdsims.py

echo "Starting"
echo '---------------------------------------------'

conda run -n $CONDA_ENV_NAME mpirun -np $MPIPROCS $PYFILE 

#End time
end=`date +%s.%N`

echo "NUM_CPUS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
