#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=48:mpiprocs=48:host=kuhpcgn1
# Name of stdout output file (default)
#PBS -o mdsim_1.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

# ---------------------------------------------------------
# 1. Configuration
# ---------------------------------------------------------
NTFY_TOPIC="kuhpchn"
NTFY_URL="https://ntfy.sh/$NTFY_TOPIC"

set -euo pipefail
export PYTHONWARNINGS="ignore::SyntaxWarning"
export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda and singularity
module load cuda
module load singularity
export PYFILE=$HOME/gitrepos/gromacs_sims/scripts/biobb_protein_ligand_simulation.py
SIF_FILE=$HOME/images/gromacs_2024.5-GPU.sif
PDB_FILE=$HOME/gitrepos/gromacs_sims/Antimicrobial_Peptides/Pseudomonas_antibiotics/simulation/parc_simulation_complexes/levparc1999C.pdb
LIGAND_CODE='LEV'
BASENAME='levparc1999C'

SINGULARITY() {
  singularity exec --nv -B ~/.Xauthority -B "${PWD}:/host_pwd" --pwd /host_pwd "$SIF_FILE" "$@"
}


echo "Starting"
echo '---------------------------------------------'
SINGULARITY bash -c "${PYFILE} --input_structure ${PDB_FILE} --ligand_code ${LIGAND_CODE} --outdir ${BASENAME} --nprocs ${PBS_NCPUS} --usegpu --protonated"


#End time
end=`date +%s.%N`

echo "NUM_CPUS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'

# Capture the exit code of your main compute task
EXIT_CODE=$?

# ---------------------------------------------------------
# 4. "Job Completed/Failed" Notification via Head Node
# ---------------------------------------------------------
if [ $EXIT_CODE -eq 0 ]; then
# Success notification
ssh -tt kuhpchn "curl -s -o /dev/null -d 'Job ID: $PBS_JOBID finished successfully.' \
    -H 'Title: ✅ Job Complete: $PBS_JOBNAME' \
    -H 'Tags: white_check_mark, tada' \
    -H 'Priority: default' \
    $NTFY_URL"
else
# Failure notification
ssh -tt kuhpchn "curl -s -o /dev/null -d 'Job ID: $PBS_JOBID failed with exit code $EXIT_CODE.' \
    -H 'Title: ❌ Job Failed: $PBS_JOBNAME' \
    -H 'Tags: x, warning' \
    -H 'Priority: high' \
    $NTFY_URL"
fi

exit $EXIT_CODE