#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N rclone_sync
#PBS -l select=1:ncpus=6:mpiprocs=6
# queue select
#PBS -q workq
# Name of stdout output file (default)
#PBS -o rclone_sync.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=48:00:00 
#----------------------------------------------------------

# Enter the name of the Login host

export LOGIN_NODE=kuhpchn
export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')


#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
export SRC=$HOME/gitrepos/gromacs_sims
export DEST=gdrive://data/GROMACS/gromacs_sims
export OUTFILE=sync_out.log
echo "Starting"
echo '---------------------------------------------'

RCLONEBIN=$HOME/.local/bin/rclone
SSHBIN=/usr/bin/ssh

$SSHBIN $LOGIN_NODE $RCLONEBIN --checkers 1 --transfers ${PBS_NCPUS} sync -P $SRC $DEST --exclude ".git/" 2>&1 | tee ${PBS_O_WORKDIR}/${OUTFILE}

#End time
end=`date +%s.%N`

export RUNTIME=$( echo "$end - $start" | bc -l )
echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
#----------------------------------------------------------
# Communicate job status to a telegram bot
#----------------------------------------------------------
# <-Create a telegram bot 
# <-Get TOKEN, CHATID from botfather
# <-See https://www.cytron.io/tutorial/how-to-create-a-telegram-bot-get-the-api-key-and-chat-id
# <-Put them into two environment variables TOKEN and CHATID 
# <-Store them in a config file and source it like below
#----------------------------------------------------------

source ${HOME}/.config/telegram/telegram.conf

LOGIN_NODE=kuhpchn
SSHBIN=/usr/bin/ssh
URL="https://api.telegram.org/bot${TOKEN}/sendMessage"
# Generate the telegram message  text
TEXT="${bell} Local Job launched on ${start} exiting @ ${HOSTNAME}:${PWD}"
CMD='curl -s --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10  -d '\""chat_id=${CHATID}&text=${TEXT}&disable_web_page_preview=true&parse_mode=markdown"\"" ${URL}"
$SSHBIN $LOGIN_NODE $CMD
