#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=32:mpiprocs=32:host=kuhpcgn2
# Name of stdout output file (default)
#PBS -o mdprod.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

IPYNB="ku04amp02_phosphatedylethanolamine.ipynb"

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
export SIFPATH=$HOME/images
export SIFIMG=gromacs_2024.4-GPU.sif

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS
#Executing command
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	jupyter nbconvert --to notebook --execute $IPYNB

#End time
end=`date +%s.%N`


echo "NUM_THREADS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'

# Define login node
LOGIN_NODE="kuhpchn"

# Define the ntfy.sh URL
NTFY_URL="https://ntfy.sh/kuhpchn"

# Define the message payload
MESSAGE="Job '$PBS_JOBID' finished on kuhpchn in '$RUNTIME' secs. Check output @ '$PBS_O_WORKDIR'"

# SSH into the login node and execute the curl command remotely
sshpass -f $HOME/.password ssh "$LOGIN_NODE" "curl -X POST -d \"$MESSAGE\" \"$NTFY_URL\""
