#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N zebhb_phz_ext
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=24:mpiprocs=24:host=kuhpcgn2
# Name of stdout output file (default)
#PBS -o zebhb_phz_ext.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=192:00:00 
#----------------------------------------------------------

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')


export MDNAME=mmp2
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
SIFPATH=$HOME/images

SIFIMG=gromacs_2024.2-GPU.sif

GPUID='0'

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS

#Actual MD Dynamics: 
LD_LIBRARY_PATH="" \
	singularity exec --nv -B ${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx mdrun -nb gpu -gpu_id $GPUID -pme gpu -pmefft gpu -pin on -v -nt $PBS_NCPUS \
	-deffnm $MDNAME -cpi ${MDNAME}.cpt


#End time
end=`date +%s.%N`

echo "OMP_NUM_THREADS=" "$PBS_NCPUS"

RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
#----------------------------------------------------------
# Communicate job status to a telegram bot
#----------------------------------------------------------
# Create a telegram bot 
# Get TOKEN, CHATID from botfather
# See https://www.cytron.io/tutorial/how-to-create-a-telegram-bot-get-the-api-key-and-chat-id
# Put them into two environment variables TOKEN and CHATID 
# Store them in a config file and source it like below
#----------------------------------------------------------

source ${HOME}/.config/telegram/telegram.conf

LOGIN_NODE=kuhpchn
SSHBIN=/usr/bin/ssh
URL="https://api.telegram.org/bot${TOKEN}/sendMessage"

# Generate the telegram message  text

TEXT="${bell} PBS job exiting now. Job name : ${PBS_JOBNAME}. Job id : ${PBS_JOBID}. Job dir : ${PBS_O_WORKDIR}. Job start-time : ${start}. Job end-time : ${end}. Job runtime : ${RUNTIME} secs."

CMD='curl -s --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10  -d '\""chat_id=${CHATID}&text=${TEXT}&disable_web_page_preview=true&parse_mode=markdown"\"" ${URL}"

$SSHBIN $LOGIN_NODE $CMD
