#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N lysozyme-EM
# queue select
#PBS -q workq
# Name of stdout output file (default)
#PBS -o gromacs_em_ku.out 
# stdout output file
#PBS -j oe
# Total number of nodes and MPI tasks/node requested
#PBS -l select=1:mpiprocs=25
#PBS -l place=scatter
#PBS -l walltime=00:55:00 
#----------------------------------------------------------
# Change to submission directory
cd $PBS_O_WORKDIR
source /opt/gromacs-2022.4/bin/GMXRC
echo starting
echo '---------------------------------------------'
num_proc=`wc -l $PBS_NODEFILE | awk '{print $1}'`
echo 'num_proc='$num_proc
echo '---------------------------------------------'
cat $PBS_NODEFILE
echo '---------------------------------------------'
export OMP_NUM_THREADS=1

export GROFILE=1AKI_solv_ions.gro
export MDPFILE=minim.mdp
export TOPOL_FILE=topol.top

export EMFILE=em

#Preprocessing 
gmx_mpi grompp -f $MDPFILE -c $GROFILE -p $TOPOL_FILE -o ${EMFILE}.tpr

#Actual EM
gmx_mpi mdrun -v -deffnm $EMFILE
