#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N colpm_pea_ext
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=32:mpiprocs=32:host=kuhpcgn2
# Name of stdout output file (default)
#PBS -o md_ext.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=192:00:00 
#----------------------------------------------------------

export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

export EXTEND_PS=50000
export MDNAME=prod_colpm_pea_complex
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
SIFPATH=$HOME/images

SIFIMG=gromacs_2024.4-GPU.sif

GPUID='0'

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS
LD_LIBRARY_PATH="" \
        singularity exec --nv -B ${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
        gmx convert-tpr -s $MDNAME.tpr -extend $EXTEND_PS -o $MDNAME.tpr

#Actual MD Dynamics: 
LD_LIBRARY_PATH="" \
	singularity exec --nv -B ${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx mdrun -nb gpu -gpu_id $GPUID -pme gpu -pmefft gpu -pin on -v -nt $PBS_NCPUS \
	-deffnm $MDNAME -cpi ${MDNAME}.cpt


#End time
end=`date +%s.%N`

echo "OMP_NUM_THREADS=" "$PBS_NCPUS"

RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
