#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N batch_docking
# queue select
#PBS -q workq
#PBS -l select=2:ncpus=32:mpiprocs=1:host=kuhpcgn1+kuhpcgn2
# Name of stdout output file (default)
#PBS -o batch_docking.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------
PYFILE="batch_docking.py"
#----------------------------------------------------------
# Get the number of nodes and mpiprocs from PBS environment variables
NODES=$(cat $PBS_NODEFILE | sort | uniq | wc -l)
MPIPROCS=$(($NODES * $PBS_NUM_PPN))
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load singularity
module load singularity
export SIFPATH=$HOME/images
export SIFIMG=AMDock.sif

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS
#Executing command
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	mpirun -np $MPIPROCS $PYFILE

#End time
end=`date +%s.%N`


echo "NUM_THREADS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
