#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_prod
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=1:mpiprocs=1
# Name of stdout output file (default)
#PBS -o mdsim_5.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=96:00:00 
#----------------------------------------------------------

set -euo pipefail
export PYTHONWARNINGS="ignore::SyntaxWarning"
export PBS_NCPUS=32
export OMP_NUM_THREADS=$PBS_NCPUS
#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda and singularity
module load cuda
module load singularity
export PYFILE=$HOME/gitrepos/gromacs_sims/scripts/biobb_protein_ligand_simulation.py
SIF_FILE=$HOME/images/gromacs_2024.5-GPU.sif
PDB_FILE=$HOME/gitrepos/gromacs_sims/Antimicrobial_Peptides/Pseudomonas_antibiotics/simulation/parc_simulation_complexes/levparc2007C_new.pdb
LIGAND_CODE='LEV'
BASENAME='levparc2007C'

SINGULARITY() {
  singularity exec --nv -B ~/.Xauthority -B "${PWD}:/host_pwd" --pwd /host_pwd "$SIF_FILE" "$@"
}


echo "Starting"
echo '---------------------------------------------'
# Add the flag --protonated if the ligand is already protonated, otherwise don't
sshpass -f $HOME/.password ssh -t kuhpcgn1 "bash -l -c 'module load ohpc cuda singularity && cd ${PBS_O_WORKDIR} && singularity exec --nv -B ~/.Xauthority -B ${PWD}:/host_pwd --pwd /host_pwd $SIF_FILE bash -c \"$PYFILE --input_structure $PDB_FILE --ligand_code $LIGAND_CODE --outdir $BASENAME --nprocs $PBS_NCPUS --usegpu\"'"

#End time
end=`date +%s.%N`

echo "NUM_CPUS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'

# Define login node
LOGIN_NODE="kuhpchn"

# Define the ntfy.sh URL
NTFY_URL="https://ntfy.sh/kuhpchn"

# Define the message payload
MESSAGE="Job '$PBS_JOBID' finished on kuhpchn in '$RUNTIME' secs. Check output @ '$PBS_O_WORKDIR'"

# SSH into the login node and execute the curl command remotely
sshpass -f $HOME/.password ssh "$LOGIN_NODE" "curl -X POST -d \"$MESSAGE\" \"$NTFY_URL\""
