#!/bin/bash
#----------------------------------------------------------
# Job name
#PBS -N md_equi
# queue select
#PBS -q workq
#PBS -l select=1:ncpus=32:mpiprocs=32:host=kuhpcgn2
# Name of stdout output file (default)
#PBS -o md_equi.out 
# stdout output file
#PBS -j oe
#PBS -l walltime=48:00:00 
#----------------------------------------------------------


export PBS_NCPUS=$(wc -l $PBS_NODEFILE | awk '{print $1}')

#Start time
start=`date +%s.%N`
# Change to submission directory
cd $PBS_O_WORKDIR
#Load basic OHPC tools
module load ohpc
#Load cuda
module load cuda
#Load singularity
module load singularity
export SIFPATH=$HOME/images
export SIFIMG=gromacs_2024.4-GPU.sif

echo "Starting"
echo '---------------------------------------------'
unset OMP_NUM_THREADS #PBS sets this and it creates problems with GROMACS
#Executing nvt equilibration
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr -maxwarn 10

LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx mdrun -nt ${PBS_NCPUS} -pin on -gpu_id "0" -nb gpu -pme gpu -pmefft gpu -deffnm nvt

#Executing npt equilibration
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -r nvt.gro -p topol.top -n index.ndx -o npt.tpr -maxwarn 10
LD_LIBRARY_PATH="" singularity exec --nv -B${PWD}:/host_pwd --pwd /host_pwd $SIFPATH/$SIFIMG \
	gmx mdrun -nt ${PBS_NCPUS} -pin on -gpu_id "0" -nb gpu -pme gpu -pmefft gpu -deffnm npt

#End time
end=`date +%s.%N`


echo "NUM_THREADS= ${PBS_NCPUS}"
RUNTIME=$( echo "$end - $start" | bc -l )

echo '---------------------------------------------'
echo "Runtime: "$RUNTIME" sec"
echo '---------------------------------------------'
